spring:
  profiles: prod

strings:
  prefix:
    controller:
      api: "/api"

twitch:
  client_id: ""
  client_secret: ""
  grant_type: ""
  api-url:
    getstreams: ""
    token: ""

nginx:
  stat-path: ""